### PR TITLE
Added get_waypoint + patches for newer firmwares

### PR DESCRIPTION
**Pull request by nik012003**
Now WiiProxy can read the Magnetometer and Attitude data, it can read rc_channels and waypoints from iNavFlight.
I also updated the readme examples to easier code.

### CODE REVIEW

**Comment by bluday** [comment]
@nik012003 Good job! What flight controller are you using?

**Comment by nik012003** [comment]
SP Racing F3 for testing
Edit: Now I tested set_channels and it works just as well as well in iNav by setting MSP_RX on in the configuration tab. I've made the get_channels function work with both iNav and MW but I can't really test it with MW.

**Comment by bluday** [comment]
@nik012003 The code looks promising, however, there are some slight changes I need to make. My current and only flight controller at the moment is the MultiWii Crius SE v2.0. I'm going to include your changes in my branch and create support for most non 32-bit boards that doesn't support CF and BF. Good job.

**Comment by nik012003** [comment]
That would be perfect!
My code is a bit janky in the decoding part of each function , but it works just fine in my tests.
At first I tried to use your decode function but I didn't really understand how it worked so I decoded each byte one by one.
It would be cool if you how that works so I can adapt my code and make it much cleaner.
Thank you very much!

**Pull request merged**
